server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Member
          uri: http://localhost:8081
          predicates:
            - Path=/members/** 
        - id: Product
          uri: http://localhost:8082
          predicates:
            - Path=/products/** 
        - id: Order
          uri: http://localhost:8083
          predicates:
            - Path=/orders/** 
        - id: Payment
          uri: http://localhost:8084
          predicates:
            - Path=/payments/** 
        - id: Delivery
          uri: http://localhost:8085
          predicates:
            - Path=/deliveries/** 
        - id: CustomerCenter
          uri: http://localhost:8086
          predicates:
            - Path= /mypages/**
        - id: Marketing
          uri: http://localhost:8087
          predicates:
            - Path=/notifications/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Member
          uri: http://Member:8080
          predicates:
            - Path=/members/** 
        - id: Product
          uri: http://Product:8080
          predicates:
            - Path=/products/** 
        - id: Order
          uri: http://Order:8080
          predicates:
            - Path=/orders/** 
        - id: Payment
          uri: http://Payment:8080
          predicates:
            - Path=/payments/** 
        - id: Delivery
          uri: http://Delivery:8080
          predicates:
            - Path=/deliveries/** 
        - id: CustomerCenter
          uri: http://CustomerCenter:8080
          predicates:
            - Path= /mypages/**
        - id: Marketing
          uri: http://Marketing:8080
          predicates:
            - Path=/notifications/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
